### ISSUE TITLE
$this->_authenticator->post() sends a get request

### ISSUE THREAD

**Issue by mwaneykm** [het-keukenmagazijn/passport-authenticator#1]
final public function post(string $endpoint, array $dataToSend = [], array $extraHeaders = []): array {
        if (!$this->isAuthenticated()) $this->_authenticate();
        return $this->sendGetRequest($endpoint, $dataToSend, $extraHeaders);
    }

**Comment by ghost** [comment]
Fixed in 1.0.1-stable.
